version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bookwise
      - POSTGRES_PASSWORD=bookwise
      - POSTGRES_DB=bookwise
    volumes:
      - bookwise_pg_data:/bitnami/postgresql

volumes:
  bookwise_pg_data: